In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("employee_raw_for_cleaning_project.csv")

In [3]:
df

,Name,Gender,Age,Education,Department,JoiningYear,ExperienceYears,Salary,PerformanceScore,LeaveOrNot
0,Employee_1,Male,34.0,Bachelors,Bangalore,2017,0,160962.0,2.0,0
1,Employee_2,Female,NaN,Bachelors,Pune,2013,3,45795.0,2.0,1
2,Employee_3,Female,38.0,Bachelors,New Delhi,2014,2,92580.0,5.0,0
3,Employee_4,Male,27.0,Masters,Bangalore,2016,5,106170.0,4.0,1
4,Employee_5,Male,24.0,Masters,Pune,2017,2,179406.0,2.0,1
...,...,...,...,...,...,...,...,...,...,...
4648,Employee_4649,Female,26.0,Bachelors,Bangalore,2013,4,151503.0,3.0,0
4649,Employee_4650,Male,37.0,Masters,Pune,2013,2,66840.0,2.0,1
4650,Employee_4651,Male,27.0,Masters,New Delhi,2018,5,107535.0,1.0,1
4651,Employee_4652,Male,30.0,Bachelors,Bangalore,2012,2,153486.0,3.0,0
4652,Employee_4653,Male,33.0,Bachelors,Bangalore,2015,4,101718.0,2.0,0

In [4]:
df.columns

Index(['Name', 'Gender', 'Age', 'Education', 'Department', 'JoiningYear',
       'ExperienceYears', 'Salary', 'PerformanceScore', 'LeaveOrNot'],
      dtype='object')

In [5]:
df.drop(columns=["LeaveOrNot"], inplace= True)

In [6]:
df.isnull().sum() * 100/ len(df)

Name                0.000000
Gender              0.000000
Age                 5.007522
Education           0.000000
Department          0.000000
JoiningYear         0.000000
ExperienceYears     0.000000
Salary              5.007522
PerformanceScore    5.007522
dtype: float64

In [7]:
df['Age'].unique()

array([34., nan, 38., 27., 24., 37., 32., 39., 29., 30., 22., 28., 36.,
       23., 31., 25., 26., 40., 35., 70., 33., 41.])

In [8]:
df['Age'] = df['Age'].fillna(0)

In [9]:
df['Age'] = df['Age'].replace(0,np.nan)

In [10]:
df['Age'] = df['Age'].fillna(df['Age'].median())

In [11]:
df

,Name,Gender,Age,Education,Department,JoiningYear,ExperienceYears,Salary,PerformanceScore
0,Employee_1,Male,34.0,Bachelors,Bangalore,2017,0,160962.0,2.0
1,Employee_2,Female,28.0,Bachelors,Pune,2013,3,45795.0,2.0
2,Employee_3,Female,38.0,Bachelors,New Delhi,2014,2,92580.0,5.0
3,Employee_4,Male,27.0,Masters,Bangalore,2016,5,106170.0,4.0
4,Employee_5,Male,24.0,Masters,Pune,2017,2,179406.0,2.0
...,...,...,...,...,...,...,...,...,...
4648,Employee_4649,Female,26.0,Bachelors,Bangalore,2013,4,151503.0,3.0
4649,Employee_4650,Male,37.0,Masters,Pune,2013,2,66840.0,2.0
4650,Employee_4651,Male,27.0,Masters,New Delhi,2018,5,107535.0,1.0
4651,Employee_4652,Male,30.0,Bachelors,Bangalore,2012,2,153486.0,3.0
4652,Employee_4653,Male,33.0,Bachelors,Bangalore,2015,4,101718.0,2.0

In [12]:
df.isnull().sum() * 100/ len(df)

Name                0.000000
Gender              0.000000
Age                 0.000000
Education           0.000000
Department          0.000000
JoiningYear         0.000000
ExperienceYears     0.000000
Salary              5.007522
PerformanceScore    5.007522
dtype: float64

In [13]:
df['PerformanceScore']

0       2.0
1       2.0
2       5.0
3       4.0
4       2.0
       ...
4648    3.0
4649    2.0
4650    1.0
4651    3.0
4652    2.0
Name: PerformanceScore, Length: 4653, dtype: float64

In [14]:
df['PerformanceScore'] = df['PerformanceScore'].fillna(0)

In [15]:
df['PerformanceScore'] = df['PerformanceScore'].replace(0,np.nan)

In [16]:
df['PerformanceScore'] = df['PerformanceScore'].fillna(df['PerformanceScore'].mean())

In [17]:
df.isnull().sum() * 100/len(df)

Name                0.000000
Gender              0.000000
Age                 0.000000
Education           0.000000
Department          0.000000
JoiningYear         0.000000
ExperienceYears     0.000000
Salary              5.007522
PerformanceScore    0.000000
dtype: float64

In [18]:
df['Salary'] = df['Salary'].fillna(0)

In [19]:
df['Salary'] = df['Salary'].replace(0,np.nan)

In [20]:
df['Salary'] = df['Salary'].fillna(df['Salary'].median())

In [21]:
df

,Name,Gender,Age,Education,Department,JoiningYear,ExperienceYears,Salary,PerformanceScore
0,Employee_1,Male,34.0,Bachelors,Bangalore,2017,0,160962.0,2.0
1,Employee_2,Female,28.0,Bachelors,Pune,2013,3,45795.0,2.0
2,Employee_3,Female,38.0,Bachelors,New Delhi,2014,2,92580.0,5.0
3,Employee_4,Male,27.0,Masters,Bangalore,2016,5,106170.0,4.0
4,Employee_5,Male,24.0,Masters,Pune,2017,2,179406.0,2.0
...,...,...,...,...,...,...,...,...,...
4648,Employee_4649,Female,26.0,Bachelors,Bangalore,2013,4,151503.0,3.0
4649,Employee_4650,Male,37.0,Masters,Pune,2013,2,66840.0,2.0
4650,Employee_4651,Male,27.0,Masters,New Delhi,2018,5,107535.0,1.0
4651,Employee_4652,Male,30.0,Bachelors,Bangalore,2012,2,153486.0,3.0
4652,Employee_4653,Male,33.0,Bachelors,Bangalore,2015,4,101718.0,2.0

In [23]:
df['PerformanceScore'] = df['PerformanceScore'].round(2)

In [24]:
df.to_csv("cleaned_csv_file.csv", index = False)